version: '3.8'

services:
  mysql:
    restart: always
    image: mysql:8.0
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_ALLOW_PUBLIC_KEY_Retrieval="true"
        - MYSQL_ssl_ciphersuites="TLS_RSA_WITH_AES_128_CBC_SHA256"
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - '3306'
    command: --default-authentication-plugin=mysql_native_password --general-log=ON --slow-query-log=ON
    volumes:
      - ./database_queries/init.sql:/docker-entrypoint-initdb.d/0.sql
      - ./database_queries/procedures.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database_queries/triggers.sql:/docker-entrypoint-initdb.d/2.sql
