version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --init-file="/data/application/init.sql"
    ports:
      - "3306:3306"
    volumes:
        - ./database_queries/init.sql:/data/application/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
